# Generated by Django 5.0.3 on 2024-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
